### ISSUE TITLE
Remove `email` dependency?

### ISSUE THREAD

**Issue by andylolz** [bsi-liberia/liberia-projects#24]
[email](https://pypi.org/project/email/) seems like it’s probably unused. Is it okay to remove?

Mostly just for python3 upgrade.

**Comment by markbrough** [comment]
Yes, OK to remove! [updateemail.py](https://github.com/bsi-liberia/liberia-projects/blob/master/updateemail.py) is the only file that does any email handling, and it doesn't use the `email` library.

**Comment by andylolz** [comment]
COOL. Thanks! (Sorry, I realise I could have figured this out!)

**Comment by markbrough** [comment]
No problem to check!!

**Comment by andylolz** [comment]
Fixed in c5f24c5.
