### ISSUE TITLE
Counterpart Funding

### ISSUE THREAD

**Issue by nathonic2002** [bsi-liberia/liberia-projects#3]
The Minister wants the dashboard to be able to capture funding from the Government of Liberia.

**Comment by markbrough** [comment]
Discussed - for now:

* add counterpart funding as a new project in the Dashboard
* add a field to allow projects to be "related" to each other. This should create links between the relevant projects (and between each other -- e.g. if there are 5 related projects then all 5 should have links to each other).
* show counterpart funding alongside a project's own funding
* consider whether we need some better way of "grouping" projects together?
* consider how to reflect this in Excel exports
